### ISSUE TITLE
More if();s and else();s

### ISSUE THREAD

**Issue by dynamyc010** [HiItsDevin/IceScript#1]
^^^NOT ENOUGH IFELSES

if this wont change next update im deleting github

![24841897 669999976_70189104_2492956364322072_3791111277913309184_n](https://user-images.githubusercontent.com/33225256/72621914-6c8c9a00-3942-11ea-9666-ed725ff1db6c.jpg)

**Comment by HiItsDevin** [comment]
Well sir...
![](https://i.hiitsdevin.dev/captures/hiitsdevin_new_811157.png)

**Comment by dynamyc010** [comment]
yeet thank you

**Comment by HiItsDevin** [comment]
_*fucking wheezing*_

**Comment by dynamyc010** [comment]
![download](https://user-images.githubusercontent.com/33225256/72622082-cdb46d80-3942-11ea-974d-b25cba0458d3.png)
here is knockoff google
take care of knockoff google

**Comment by HiItsDevin** [comment]
> ![download](https://user-images.githubusercontent.com/33225256/72622082-cdb46d80-3942-11ea-974d-b25cba0458d3.png)
> here is knockoff google
> take care of knockoff google

+1

**Comment by HiItsDevin** [comment]
oopsie doopsie, i pulled a fucky wucky uwu
